-- Data export for the Supabase SQL Editor, for projects where `pg_dump` is not
-- an option. Two reasons that happens: Free plan has no downloadable backups,
-- and a managed Postgres port is frequently unreachable from the machine doing
-- the work (blocked egress, or an IPv6-only project endpoint).
--
-- How to use:
--   1. Paste this whole file into the SQL Editor and Run. It only creates a
--      helper function; it changes no data.
--   2. Run:  select export_kv_data();
--   3. Click the single result cell, copy it, save as kv-data-backup.sql
--      somewhere off this machine.
--   4. To restore: paste that file into the SQL Editor and Run. Every statement
--      is `on conflict do nothing`, so re-running it is harmless.
--
-- Scope and limits, stated plainly:
--   * Covers the seven application tables. Does NOT cover `auth.users` -- losing
--     those means re-inviting staff, not losing orders.
--   * Captures current rows, not schema. Rolling back a migration means
--     re-applying the earlier migrations; this file restores the data.
--   * The column list is read from the catalog, not hard-coded, so it works
--     against the live schema whatever migrations have actually been applied.
--   * If the result cell looks truncated, the data is too large for one cell.
--     Export the big tables via Table Editor -> CSV instead.

create or replace function public.export_kv_data()
returns text
language plpgsql
stable
as $$
declare
  tbl        text;
  cols       text;      -- "id", "name", ...      in ordinal order
  vals_expr  text;      -- quote_nullable(t."id"), ...
  one_table  text;
  out_text   text := '-- Kaal Vastr data export' || E'\n'
                 || '-- generated by export_kv_data()' || E'\n'
                 || '-- restore: paste this file into the SQL Editor and Run' || E'\n';
  present    int;
begin
  foreach tbl in array array[
    'profiles', 'products', 'business_settings', 'addresses',
    'orders', 'order_items', 'staff_account_events'
  ] loop
    -- A nested block so one unreadable table cannot abandon the whole export.
    begin
      select count(*) into present
      from information_schema.tables
      where table_schema = 'public' and table_name = tbl;

      if present = 0 then
        out_text := out_text
          || format(E'\n\n-- ===== %s : not present in this database, skipped =====', tbl);
        continue;
      end if;

      -- Keep every column that can hold a real value. Only identity and
      -- always-generated columns are unusable in an INSERT, so they are the
      -- only ones excluded -- filtering on "has a default" would quietly throw
      -- away every created_at.
      select
        string_agg(format('%I', column_name), ', ' order by ordinal_position),
        'concat_ws(' || quote_literal(', ') || ', ' || string_agg(
          format('quote_nullable(t.%I)', column_name), ', ' order by ordinal_position
        ) || ')'
      into cols, vals_expr
      from information_schema.columns
      where table_schema = 'public'
        and table_name = tbl
        and is_generated <> 'ALWAYS'
        and is_identity <> 'YES';

      if cols is null then
        out_text := out_text
          || format(E'\n\n-- ===== %s : no insertable columns, skipped =====', tbl);
        continue;
      end if;

      -- Values come from quote_nullable() on the real typed columns, never from
      -- a jsonb detour. Two reasons that matters:
      --   * quote_nullable() renders an array as {S,M,L}, which is valid input
      --     syntax. Going through to_jsonb would produce ["S", "M", "L"], which
      --     is not, and the restore would fail with "malformed array literal".
      --   * the value list is built from the same ordinal-ordered list as the
      --     column list, so values cannot drift out of alignment with columns.
      -- quote_nullable() returns the bare word NULL for empty values, so they
      -- restore as NULL rather than the string 'null'.
      --
      -- concat_ws() joins them because its arguments are a proper comma list,
      -- whereas a hand-built `a || b, c || d` expression would let the comma
      -- split into two columns. concat_ws skips NULL arguments, but
      -- quote_nullable() never returns SQL NULL, so nothing is ever dropped.
      --
      -- The value list is built inside the subquery, where the `t` alias is in
      -- scope; the outer format() then just reads the finished `vals` column.
      -- vals_expr is inlined as raw SQL, not quote_literal'd -- quoting it
      -- would turn the expression into a string and emit it verbatim instead of
      -- evaluating it. It is safe to inline because every identifier in it went
      -- through format('%I', ...).
      execute 'select string_agg(format('
        || quote_literal('insert into public.%I (%s) values (%s) on conflict do nothing;')
        || ', ' || quote_literal(tbl) || ', ' || quote_literal(cols) || ', vals)'
        || ', ' || quote_literal(E'\n') || ' order by rn) '
        || 'from ( select row_number() over () as rn, '
        || vals_expr || ' as vals '
        || 'from public.' || quote_ident(tbl) || ' t ) s where vals is not null'
      into one_table;

      out_text := out_text
        || format(E'\n\n-- ===== %s =====%s%s', tbl, E'\n',
                  coalesce(one_table, '-- (no rows)'));

    exception when others then
      out_text := out_text
        || format(E'\n\n-- ===== %s FAILED: %s =====', tbl, sqlerrm);
    end;
  end loop;

  return out_text;
end;
$$;

select 'helper created - now run:  select export_kv_data();' as next_step;
